base:
  base_gzh_url: https://api.weixin.qq.com
  base_php_url: http://47.107.116.139

log:
  log_name: logs_
  log_level: info
  log_format: '[%(asctime)s]  %(filename)s->%(funcName)s line:%(lineno)d [%(levelname)s] %(message)s'
